#!/usr/bin/env python3
"""
NETRA ERP - Comprehensive Frontend Route Tester
Tests all routes for blank pages and errors
"""

import asyncio
import json
from datetime import datetime

# All routes to test (static routes only, no dynamic :params)
ROUTES_TO_TEST = [
    "/",
    "/login",
    "/my-attendance",
    "/my-leaves",
    "/my-salary-slips",
    "/my-expenses",
    "/my-drafts",
    "/my-details",
    "/sales-dashboard",
    "/leads",
    "/manager-leads",
    "/sales-meetings",
    "/follow-ups",
    "/targets",
    "/target-management",
    "/sales-funnel/pricing-plans",
    "/sales-funnel/quotations",
    "/sales-funnel/sow-list",
    "/sales-funnel/agreements",
    "/sales-funnel/payment-verification",
    "/sales-funnel/proforma-invoice",
    "/hr-dashboard",
    "/employees",
    "/onboarding",
    "/attendance",
    "/attendance-approvals",
    "/leave-management",
    "/payroll",
    "/payroll-summary-report",
    "/ctc-designer",
    "/letter-management",
    "/expenses",
    "/expense-approvals",
    "/consulting-dashboard",
    "/consultant-dashboard",
    "/projects",
    "/consulting/projects",
    "/consulting/my-projects",
    "/consulting/payments",
    "/consulting/sow-changes",
    "/timesheets",
    "/gantt-chart",
    "/admin-dashboard",
    "/admin-masters",
    "/user-management",
    "/role-management",
    "/permission-manager",
    "/permission-dashboard",
    "/employee-permissions",
    "/department-access",
    "/password-management",
    "/email-templates",
    "/email-settings",
    "/security-audit",
    "/workflow",
    "/downloads",
    "/reports",
    "/performance-dashboard",
    "/consultant-performance",
    "/team-performance",
    "/team-workload",
    "/employee-scorecard",
    "/org-chart",
    "/chat",
    "/ai-assistant",
    "/notifications",
    "/meetings",
    "/document-center",
    "/document-builder",
    "/agreements",
    "/quotations",
    "/invoices",
    "/sow-list",
    "/profile",
    "/mobile-app",
    "/tutorials",
    "/clients",
    "/consultants",
    "/approvals",
    "/payments",
    "/kickoff-requests",
    "/go-live",
    "/staffing-requests",
    "/office-locations",
    "/letterhead-settings",
    "/handover-alerts",
    "/travel-reimbursement",
    "/flow-diagram",
    "/project-roadmap",
    "/client-onboarding",
    "/consulting-meetings",
    "/attendance-leave-settings",
    "/hr-attendance-input",
    "/hr-leave-input",
]

print(f"Total routes to test: {len(ROUTES_TO_TEST)}")
print(json.dumps(ROUTES_TO_TEST, indent=2))
