import React, { useState, useContext, useRef } from 'react';
import { AuthContext } from '../App';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Progress } from '../components/ui/progress';
import { Input } from '../components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '../components/ui/collapsible';
import { 
  FileText, Download, Search, Filter, Users, CheckCircle, 
  XCircle, Clock, AlertCircle, ChevronDown, ChevronRight,
  Calendar, Building2, User, MessageSquare, Send, MapPin,
  ArrowRight, RefreshCw, Printer
} from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { toast } from 'sonner';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import PageHeader from '../components/ui/page-header';

const API = process.env.REACT_APP_BACKEND_URL;

const ManagerMOMReview = () => {
  const { user } = useContext(AuthContext);
  const [period, setPeriod] = useState('month');
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [expandedEmployees, setExpandedEmployees] = useState({});
  const [selectedView, setSelectedView] = useState('by-employee');

  // Fetch MOM review data
  const { data: reviewData, isLoading, refetch } = useQuery({
    queryKey: ['manager-mom-review', period],
    queryFn: async () => {
      const response = await axios.get(`${API}/api/analytics/manager-mom-review?period=${period}`);
      return response.data;
    },
    staleTime: 2 * 60 * 1000,
  });

  const toggleEmployeeExpand = (employeeId) => {
    setExpandedEmployees(prev => ({
      ...prev,
      [employeeId]: !prev[employeeId]
    }));
  };

  const expandAll = () => {
    const allExpanded = {};
    reviewData?.employee_summaries?.forEach(emp => {
      allExpanded[emp.employee_id] = true;
    });
    setExpandedEmployees(allExpanded);
  };

  const collapseAll = () => {
    setExpandedEmployees({});
  };

  // Filter employees based on search and filter
  const filteredEmployees = reviewData?.employee_summaries?.filter(emp => {
    const matchesSearch = !searchTerm || 
      emp.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      emp.employee_code?.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesFilter = filterStatus === 'all' ||
      (filterStatus === 'complete' && emp.completion_rate >= 100) ||
      (filterStatus === 'partial' && emp.completion_rate > 0 && emp.completion_rate < 100) ||
      (filterStatus === 'none' && emp.completion_rate === 0);
    
    return matchesSearch && matchesFilter;
  }) || [];

  // Filter all meetings for list view
  const filteredMeetings = reviewData?.all_meetings?.filter(meeting => {
    const matchesSearch = !searchTerm || 
      meeting.employee_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      meeting.company?.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesFilter = filterStatus === 'all' ||
      (filterStatus === 'complete' && meeting.has_mom) ||
      (filterStatus === 'none' && !meeting.has_mom);
    
    return matchesSearch && matchesFilter;
  }) || [];

  // Generate PDF Report
  const generatePDF = () => {
    try {
      const doc = new jsPDF('l', 'mm', 'a4'); // Landscape for more detail
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Title
      doc.setFontSize(18);
      doc.setTextColor(30, 30, 30);
      doc.text('MOM Review Report - Team Performance', pageWidth / 2, 15, { align: 'center' });
      
      // Subtitle with date range
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      const periodText = period === 'week' ? 'This Week' : period === 'month' ? 'This Month' : period === 'quarter' ? 'This Quarter' : 'This Year';
      doc.text(`Period: ${periodText} | Generated: ${new Date().toLocaleDateString()} | Generated By: ${user?.name || 'Manager'}`, pageWidth / 2, 22, { align: 'center' });
      
      // Overall Summary Box
      doc.setFillColor(240, 249, 255);
      doc.roundedRect(14, 28, pageWidth - 28, 20, 3, 3, 'F');
      doc.setFontSize(9);
      doc.setTextColor(30, 30, 30);
      
      const summary = reviewData?.overall_summary || {};
      doc.text(`Total Reportees: ${summary.total_reportees || 0}`, 20, 36);
      doc.text(`Total Meetings: ${summary.total_meetings || 0}`, 70, 36);
      doc.text(`With MOM: ${summary.meetings_with_mom || 0}`, 120, 36);
      doc.text(`Without MOM: ${summary.meetings_without_mom || 0}`, 160, 36);
      doc.text(`Completion Rate: ${summary.mom_completion_rate || 0}%`, 210, 36);
      doc.text(`Sent to Client: ${summary.mom_sent_to_client || 0}`, 260, 36);
      
      let yPos = 55;
      
      // Employee Summary Table
      doc.setFontSize(12);
      doc.setTextColor(30, 30, 30);
      doc.text('Employee MOM Summary', 14, yPos);
      yPos += 5;
      
      const employeeSummaryData = (filteredEmployees || []).map(emp => [
        emp.employee_code || '-',
        emp.name || 'Unknown',
        emp.role || '-',
        emp.total_meetings || 0,
        emp.with_mom || 0,
        emp.without_mom || 0,
        `${emp.completion_rate || 0}%`,
        emp.sent_to_client || 0
      ]);
      
      doc.autoTable({
        startY: yPos,
        head: [['Emp ID', 'Name', 'Role', 'Total', 'With MOM', 'Without MOM', 'Rate', 'Sent']],
        body: employeeSummaryData,
        theme: 'striped',
        headStyles: { fillColor: [59, 130, 246], textColor: 255, fontSize: 8 },
        bodyStyles: { fontSize: 7 },
        columnStyles: {
          0: { cellWidth: 25 },
          1: { cellWidth: 45 },
          2: { cellWidth: 35 },
          3: { cellWidth: 20 },
          4: { cellWidth: 25 },
          5: { cellWidth: 30 },
          6: { cellWidth: 20 },
          7: { cellWidth: 20 }
        }
      });
      
      // Add detailed meeting list on new page
      doc.addPage();
      yPos = 15;
      doc.setFontSize(14);
      doc.text('Detailed Meeting Records with MOM', 14, yPos);
      yPos += 8;
      
      // Meeting details table
      const meetingData = (filteredMeetings || []).slice(0, 100).map(meeting => [
        meeting.meeting_date ? new Date(meeting.meeting_date).toLocaleDateString() : '-',
        meeting.employee_name || '-',
        meeting.company || '-',
        meeting.title?.substring(0, 30) || '-',
        meeting.mode || '-',
        meeting.has_mom ? 'Yes' : 'No',
        meeting.mom_sent_to_client ? 'Yes' : 'No',
        meeting.mom?.summary?.substring(0, 50) || '-'
      ]);
      
      doc.autoTable({
        startY: yPos,
        head: [['Date', 'Employee', 'Company', 'Title', 'Mode', 'MOM', 'Sent', 'Summary']],
        body: meetingData,
        theme: 'striped',
        headStyles: { fillColor: [59, 130, 246], textColor: 255, fontSize: 7 },
        bodyStyles: { fontSize: 6 },
        columnStyles: {
          0: { cellWidth: 22 },
          1: { cellWidth: 30 },
          2: { cellWidth: 35 },
          3: { cellWidth: 35 },
          4: { cellWidth: 18 },
          5: { cellWidth: 15 },
          6: { cellWidth: 15 },
          7: { cellWidth: 80 }
        }
      });
      
      // Add detailed MOM content for meetings with MOM
      const meetingsWithMOM = (filteredMeetings || []).filter(m => m.has_mom && m.mom?.summary);
      if (meetingsWithMOM.length > 0) {
        doc.addPage();
        yPos = 15;
        doc.setFontSize(14);
        doc.text('Detailed MOM Content', 14, yPos);
        yPos += 10;
        
        (meetingsWithMOM || []).slice(0, 20).forEach((meeting, idx) => {
          if (yPos > 180) {
            doc.addPage();
            yPos = 15;
          }
          
          // Meeting header
          doc.setFillColor(249, 250, 251);
          doc.roundedRect(14, yPos - 4, pageWidth - 28, 8, 1, 1, 'F');
          doc.setFontSize(9);
          doc.setTextColor(30, 30, 30);
          doc.text(`${idx + 1}. ${meeting.company} - ${meeting.title} (${meeting.employee_name})`, 16, yPos);
          doc.setFontSize(7);
          doc.setTextColor(100, 100, 100);
          doc.text(`Date: ${meeting.meeting_date ? new Date(meeting.meeting_date).toLocaleDateString() : '-'}`, pageWidth - 50, yPos);
          yPos += 10;
          
          // MOM Summary
          doc.setFontSize(8);
          doc.setTextColor(30, 30, 30);
          if (meeting.mom?.summary) {
            doc.text('Summary:', 16, yPos);
            yPos += 4;
            doc.setFontSize(7);
            const summaryLines = doc.splitTextToSize(meeting.mom.summary, pageWidth - 40);
            doc.text(summaryLines.slice(0, 3), 20, yPos);
            yPos += summaryLines.slice(0, 3).length * 3.5 + 2;
          }
          
          // Key Decisions
          if (meeting.mom?.key_decisions?.length > 0) {
            doc.setFontSize(8);
            doc.text('Key Decisions:', 16, yPos);
            yPos += 4;
            doc.setFontSize(7);
            (meeting?.mom?.key_decisions || []).slice(0, 3).forEach(decision => {
              doc.text(`• ${decision.substring(0, 100)}`, 20, yPos);
              yPos += 3.5;
            });
            yPos += 2;
          }
          
          // Commitments Made
          if (meeting.mom?.commitments_made?.length > 0) {
            doc.setFontSize(8);
            doc.text('Commitments Made:', 16, yPos);
            yPos += 4;
            doc.setFontSize(7);
            (meeting?.mom?.commitments_made || []).slice(0, 3).forEach(commitment => {
              doc.text(`• ${commitment.substring(0, 100)}`, 20, yPos);
              yPos += 3.5;
            });
            yPos += 2;
          }
          
          // Client Concerns
          if (meeting.mom?.client_concerns?.length > 0) {
            doc.setFontSize(8);
            doc.setTextColor(180, 100, 0);
            doc.text('Client Concerns:', 16, yPos);
            yPos += 4;
            doc.setFontSize(7);
            doc.setTextColor(30, 30, 30);
            (meeting?.mom?.client_concerns || []).slice(0, 2).forEach(concern => {
              doc.text(`• ${concern.substring(0, 100)}`, 20, yPos);
              yPos += 3.5;
            });
            yPos += 2;
          }
          
          yPos += 5;
        });
      }
      
      // Footer on all pages
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount} | DVBC NETRA ERP - MOM Review Report`, pageWidth / 2, 205, { align: 'center' });
      }
      
      // Save PDF
      const fileName = `MOM_Review_Report_${period}_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      toast.success('PDF report downloaded successfully');
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate PDF report');
    }
  };

  const getCompletionColor = (rate) => {
    if (rate >= 90) return 'bg-green-100 text-green-800 border-green-200';
    if (rate >= 70) return 'bg-amber-100 text-amber-800 border-amber-200';
    if (rate >= 50) return 'bg-orange-100 text-orange-800 border-orange-200';
    return 'bg-red-100 text-red-800 border-red-200';
  };

  const summary = reviewData?.overall_summary || {};

  return (
    <div className="space-y-6 p-6" data-testid="manager-mom-review">
      <PageHeader 
        title="MOM Review - Team Performance"
        subtitle="Review and verify Minutes of Meeting submissions by your team"
      />

      {/* Controls */}
      <Card className="border-zinc-200">
        <CardContent className="py-4">
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-zinc-500" />
              <Select value={period} onValueChange={setPeriod}>
                <SelectTrigger className="w-[140px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="week">This Week</SelectItem>
                  <SelectItem value="month">This Month</SelectItem>
                  <SelectItem value="quarter">This Quarter</SelectItem>
                  <SelectItem value="year">This Year</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center gap-2 flex-1 min-w-[200px]">
              <Search className="w-4 h-4 text-zinc-500" />
              <Input
                placeholder="Search by name, company..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="max-w-xs"
              />
            </div>

            <div className="flex items-center gap-2">
              <Filter className="w-4 h-4 text-zinc-500" />
              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-[150px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="complete">100% Complete</SelectItem>
                  <SelectItem value="partial">Partial</SelectItem>
                  <SelectItem value="none">No MOM</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center gap-2 ml-auto">
              <Button variant="outline" size="sm" onClick={() => refetch()}>
                <RefreshCw className="w-4 h-4 mr-1" />
                Refresh
              </Button>
              <Button 
                variant="default" 
                size="sm" 
                onClick={generatePDF}
                className="bg-blue-600 hover:bg-blue-700"
                data-testid="download-pdf-btn"
              >
                <Download className="w-4 h-4 mr-1" />
                Download PDF
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Overall Summary */}
      <div className="grid grid-cols-2 md:grid-cols-6 gap-4">
        <Card className="border-zinc-200">
          <CardContent className="py-4 text-center">
            <Users className="w-6 h-6 mx-auto mb-2 text-blue-600" />
            <div className="text-2xl font-bold">{summary.total_reportees || 0}</div>
            <div className="text-xs text-zinc-500">Team Members</div>
          </CardContent>
        </Card>
        <Card className="border-zinc-200">
          <CardContent className="py-4 text-center">
            <MessageSquare className="w-6 h-6 mx-auto mb-2 text-indigo-600" />
            <div className="text-2xl font-bold">{summary.total_meetings || 0}</div>
            <div className="text-xs text-zinc-500">Total Meetings</div>
          </CardContent>
        </Card>
        <Card className="border-zinc-200 bg-green-50">
          <CardContent className="py-4 text-center">
            <CheckCircle className="w-6 h-6 mx-auto mb-2 text-green-600" />
            <div className="text-2xl font-bold text-green-700">{summary.meetings_with_mom || 0}</div>
            <div className="text-xs text-green-600">With MOM</div>
          </CardContent>
        </Card>
        <Card className="border-zinc-200 bg-red-50">
          <CardContent className="py-4 text-center">
            <XCircle className="w-6 h-6 mx-auto mb-2 text-red-600" />
            <div className="text-2xl font-bold text-red-700">{summary.meetings_without_mom || 0}</div>
            <div className="text-xs text-red-600">Without MOM</div>
          </CardContent>
        </Card>
        <Card className="border-zinc-200">
          <CardContent className="py-4 text-center">
            <div className="text-3xl font-bold text-blue-600">{summary.mom_completion_rate || 0}%</div>
            <div className="text-xs text-zinc-500">Completion Rate</div>
            <Progress value={summary.mom_completion_rate || 0} className="h-1.5 mt-2" />
          </CardContent>
        </Card>
        <Card className="border-zinc-200 bg-blue-50">
          <CardContent className="py-4 text-center">
            <Send className="w-6 h-6 mx-auto mb-2 text-blue-600" />
            <div className="text-2xl font-bold text-blue-700">{summary.mom_sent_to_client || 0}</div>
            <div className="text-xs text-blue-600">Sent to Client</div>
          </CardContent>
        </Card>
      </div>

      {/* View Tabs */}
      <Tabs value={selectedView} onValueChange={setSelectedView}>
        <div className="flex items-center justify-between">
          <TabsList>
            <TabsTrigger value="by-employee">By Employee</TabsTrigger>
            <TabsTrigger value="all-meetings">All Meetings</TabsTrigger>
          </TabsList>
          {selectedView === 'by-employee' && (
            <div className="flex gap-2">
              <Button variant="ghost" size="sm" onClick={expandAll}>
                Expand All
              </Button>
              <Button variant="ghost" size="sm" onClick={collapseAll}>
                Collapse All
              </Button>
            </div>
          )}
        </div>

        {/* By Employee View */}
        <TabsContent value="by-employee" className="space-y-3 mt-4">
          {isLoading ? (
            <div className="text-center py-8 text-zinc-500">Loading...</div>
          ) : filteredEmployees.length === 0 ? (
            <div className="text-center py-8 text-zinc-500">No data found</div>
          ) : (
            (filteredEmployees || []).map((employee) => (
              <Collapsible 
                key={employee.employee_id} 
                open={expandedEmployees[employee.employee_id]}
                onOpenChange={() => toggleEmployeeExpand(employee.employee_id)}
              >
                <Card className="border-zinc-200">
                  <CollapsibleTrigger className="w-full">
                    <CardContent className="py-3">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-4">
                          {expandedEmployees[employee.employee_id] ? (
                            <ChevronDown className="w-5 h-5 text-zinc-400" />
                          ) : (
                            <ChevronRight className="w-5 h-5 text-zinc-400" />
                          )}
                          <div className="text-left">
                            <div className="flex items-center gap-2">
                              <span className="font-medium">{employee.name}</span>
                              <Badge variant="outline" className="text-xs">{employee.employee_code}</Badge>
                              <Badge variant="secondary" className="text-xs">{employee.role}</Badge>
                            </div>
                            <div className="text-xs text-zinc-500 mt-1">
                              {employee.department}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-6">
                          <div className="text-center">
                            <div className="text-lg font-semibold">{employee.total_meetings}</div>
                            <div className="text-xs text-zinc-500">Total</div>
                          </div>
                          <div className="text-center">
                            <div className="text-lg font-semibold text-green-600">{employee.with_mom}</div>
                            <div className="text-xs text-zinc-500">With MOM</div>
                          </div>
                          <div className="text-center">
                            <div className="text-lg font-semibold text-red-600">{employee.without_mom}</div>
                            <div className="text-xs text-zinc-500">Pending</div>
                          </div>
                          <Badge className={`${getCompletionColor(employee.completion_rate)} px-3 py-1`}>
                            {employee.completion_rate}%
                          </Badge>
                        </div>
                      </div>
                    </CardContent>
                  </CollapsibleTrigger>
                  
                  <CollapsibleContent>
                    <div className="border-t px-4 py-3 bg-zinc-50/50">
                      <div className="space-y-3">
                        {employee.meetings?.map((meeting, idx) => (
                          <div 
                            key={meeting.id || idx} 
                            className={`p-3 rounded-lg border ${meeting.has_mom ? 'bg-white border-green-200' : 'bg-red-50 border-red-200'}`}
                          >
                            <div className="flex items-start justify-between mb-2">
                              <div>
                                <div className="flex items-center gap-2">
                                  <Building2 className="w-4 h-4 text-zinc-400" />
                                  <span className="font-medium">{meeting.company}</span>
                                  <Badge variant="outline" className="text-xs capitalize">{meeting.mode}</Badge>
                                  {meeting.has_mom ? (
                                    <Badge className="bg-green-100 text-green-800 text-xs">MOM Recorded</Badge>
                                  ) : (
                                    <Badge className="bg-red-100 text-red-800 text-xs">No MOM</Badge>
                                  )}
                                  {meeting.mom_sent_to_client && (
                                    <Badge className="bg-blue-100 text-blue-800 text-xs">
                                      <Send className="w-3 h-3 mr-1" />
                                      Sent
                                    </Badge>
                                  )}
                                </div>
                                <div className="text-sm text-zinc-600 mt-1">{meeting.title}</div>
                              </div>
                              <div className="text-right text-sm text-zinc-500">
                                <div className="flex items-center gap-1">
                                  <Calendar className="w-3 h-3" />
                                  {meeting.meeting_date ? new Date(meeting.meeting_date).toLocaleDateString() : '-'}
                                </div>
                                {meeting.meeting_time && <div>{meeting.meeting_time}</div>}
                              </div>
                            </div>
                            
                            {/* MOM Details */}
                            {meeting.has_mom && meeting.mom && (
                              <div className="mt-3 space-y-2 text-sm">
                                {meeting.mom.summary && (
                                  <div className="bg-zinc-100 p-2 rounded">
                                    <span className="font-medium text-zinc-700">Summary: </span>
                                    <span className="text-zinc-600">{meeting.mom.summary}</span>
                                  </div>
                                )}
                                
                                {meeting.mom.key_decisions?.length > 0 && (
                                  <div>
                                    <span className="font-medium text-zinc-700">Key Decisions:</span>
                                    <ul className="ml-4 mt-1 space-y-1">
                                      {(meeting?.mom?.key_decisions || []).map((decision, i) => (
                                        <li key={i} className="flex items-start gap-2 text-zinc-600">
                                          <CheckCircle className="w-3 h-3 text-green-500 mt-1 flex-shrink-0" />
                                          {decision}
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                                
                                {meeting.mom.commitments_made?.length > 0 && (
                                  <div>
                                    <span className="font-medium text-zinc-700">Commitments Made:</span>
                                    <ul className="ml-4 mt-1 space-y-1">
                                      {(meeting?.mom?.commitments_made || []).map((commitment, i) => (
                                        <li key={i} className="flex items-start gap-2 text-zinc-600">
                                          <ArrowRight className="w-3 h-3 text-blue-500 mt-1 flex-shrink-0" />
                                          {commitment}
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                                
                                {meeting.mom.client_concerns?.length > 0 && (
                                  <div className="bg-amber-50 p-2 rounded">
                                    <span className="font-medium text-amber-700">Client Concerns:</span>
                                    <ul className="ml-4 mt-1 space-y-1">
                                      {(meeting?.mom?.client_concerns || []).map((concern, i) => (
                                        <li key={i} className="flex items-start gap-2 text-amber-800">
                                          <AlertCircle className="w-3 h-3 text-amber-500 mt-1 flex-shrink-0" />
                                          {concern}
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                                
                                {meeting.mom.next_steps?.length > 0 && (
                                  <div>
                                    <span className="font-medium text-zinc-700">Next Steps:</span>
                                    <ul className="ml-4 mt-1 space-y-1">
                                      {(meeting?.mom?.next_steps || []).map((step, i) => (
                                        <li key={i} className="flex items-start gap-2 text-zinc-600">
                                          <Clock className="w-3 h-3 text-indigo-500 mt-1 flex-shrink-0" />
                                          {step}
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                                
                                {meeting.mom.recorded_by && (
                                  <div className="text-xs text-zinc-400 mt-2">
                                    Recorded by {meeting.mom.recorded_by}
                                    {meeting.mom.recorded_at && ` on ${new Date(meeting.mom.recorded_at).toLocaleString()}`}
                                  </div>
                                )}
                              </div>
                            )}
                            
                            {/* Travel Info */}
                            {meeting.travel_info && (
                              <div className="mt-2 flex items-center gap-2 text-xs text-zinc-500">
                                <MapPin className="w-3 h-3" />
                                {meeting.travel_info.origin} → {meeting.travel_info.destination}
                                ({meeting.travel_info.distance_km} km via {meeting.travel_info.travel_mode})
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  </CollapsibleContent>
                </Card>
              </Collapsible>
            ))
          )}
        </TabsContent>

        {/* All Meetings View */}
        <TabsContent value="all-meetings" className="mt-4">
          <Card className="border-zinc-200">
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-zinc-50 border-b">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-zinc-500">Date</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-zinc-500">Employee</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-zinc-500">Company</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-zinc-500">Title</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-zinc-500">Mode</th>
                      <th className="px-4 py-3 text-center text-xs font-medium text-zinc-500">MOM</th>
                      <th className="px-4 py-3 text-center text-xs font-medium text-zinc-500">Sent</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-zinc-500">Summary</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-zinc-100">
                    {(filteredMeetings || []).map((meeting, idx) => (
                      <tr key={meeting.id || idx} className="hover:bg-zinc-50">
                        <td className="px-4 py-3 text-sm">
                          {meeting.meeting_date ? new Date(meeting.meeting_date).toLocaleDateString() : '-'}
                        </td>
                        <td className="px-4 py-3">
                          <div className="text-sm font-medium">{meeting.employee_name}</div>
                          <div className="text-xs text-zinc-500">{meeting.employee_code}</div>
                        </td>
                        <td className="px-4 py-3 text-sm">{meeting.company}</td>
                        <td className="px-4 py-3 text-sm max-w-[200px] truncate">{meeting.title}</td>
                        <td className="px-4 py-3">
                          <Badge variant="outline" className="text-xs capitalize">{meeting.mode}</Badge>
                        </td>
                        <td className="px-4 py-3 text-center">
                          {meeting.has_mom ? (
                            <CheckCircle className="w-5 h-5 text-green-500 mx-auto" />
                          ) : (
                            <XCircle className="w-5 h-5 text-red-400 mx-auto" />
                          )}
                        </td>
                        <td className="px-4 py-3 text-center">
                          {meeting.mom_sent_to_client ? (
                            <Send className="w-4 h-4 text-blue-500 mx-auto" />
                          ) : (
                            <span className="text-zinc-300">-</span>
                          )}
                        </td>
                        <td className="px-4 py-3 text-sm text-zinc-600 max-w-[300px] truncate">
                          {meeting.mom?.summary || '-'}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {filteredMeetings.length === 0 && (
                <div className="text-center py-8 text-zinc-500">No meetings found</div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default ManagerMOMReview;
